export const currencies = [
  {
    country: "Afghanistan",
    currency: "Afghan Afghani",
    code: "AFN",
    icon: "https://flagcdn.com/w20/af.png",
  },
  {
    country: "Albania",
    currency: "Albanian Lek",
    code: "ALL",
    icon: "https://flagcdn.com/w20/al.png",
  },
  {
    country: "Algeria",
    currency: "Algerian Dinar",
    code: "DZD",
    icon: "https://flagcdn.com/w20/dz.png",
  },
  {
    country: "Andorra",
    currency: "Euro",
    code: "EUR",
    icon: "https://flagcdn.com/w20/ad.png",
  },
  {
    country: "Angola",
    currency: "Angolan Kwanza",
    code: "AOA",
    icon: "https://flagcdn.com/w20/ao.png",
  },
  {
    country: "Argentina",
    currency: "Argentine Peso",
    code: "ARS",
    icon: "https://flagcdn.com/w20/ar.png",
  },
  {
    country: "Armenia",
    currency: "Armenian Dram",
    code: "AMD",
    icon: "https://flagcdn.com/w20/am.png",
  },
  {
    country: "Australia",
    currency: "Australian Dollar",
    code: "AUD",
    icon: "https://flagcdn.com/w20/au.png",
  },
  {
    country: "Austria",
    currency: "Euro",
    code: "EUR",
    icon: "https://flagcdn.com/w20/at.png",
  },
  {
    country: "Azerbaijan",
    currency: "Azerbaijani Manat",
    code: "AZN",
    icon: "https://flagcdn.com/w20/az.png",
  },
  {
    country: "Bahamas",
    currency: "Bahamian Dollar",
    code: "BSD",
    icon: "https://flagcdn.com/w20/bs.png",
  },
  {
    country: "Bahrain",
    currency: "Bahraini Dinar",
    code: "BHD",
    icon: "https://flagcdn.com/w20/bh.png",
  },
  {
    country: "Bangladesh",
    currency: "Bangladeshi Taka",
    code: "BDT",
    icon: "https://flagcdn.com/w20/bd.png",
  },
  {
    country: "Belarus",
    currency: "Belarusian Ruble",
    code: "BYN",
    icon: "https://flagcdn.com/w20/by.png",
  },
  {
    country: "Belgium",
    currency: "Euro",
    code: "EUR",
    icon: "https://flagcdn.com/w20/be.png",
  },
  {
    country: "Belize",
    currency: "Belize Dollar",
    code: "BZD",
    icon: "https://flagcdn.com/w20/bz.png",
  },
  {
    country: "Benin",
    currency: "West African CFA franc",
    code: "XOF",
    icon: "https://flagcdn.com/w20/bj.png",
  },
  {
    country: "Bhutan",
    currency: "Bhutanese Ngultrum",
    code: "BTN",
    icon: "https://flagcdn.com/w20/bt.png",
  },
  {
    country: "Bolivia",
    currency: "Bolivian Boliviano",
    code: "BOB",
    icon: "https://flagcdn.com/w20/bo.png",
  },
  {
    country: "Bosnia and Herzegovina",
    currency: "Bosnia and Herzegovina Convertible Mark",
    code: "BAM",
    icon: "https://flagcdn.com/w20/ba.png",
  },
  {
    country: "Botswana",
    currency: "Botswana Pula",
    code: "BWP",
    icon: "https://flagcdn.com/w20/bw.png",
  },
  {
    country: "Brazil",
    currency: "Brazilian Real",
    code: "BRL",
    icon: "https://flagcdn.com/w20/br.png",
  },
  {
    country: "Brunei",
    currency: "Brunei Dollar",
    code: "BND",
    icon: "https://flagcdn.com/w20/bn.png",
  },
  {
    country: "Bulgaria",
    currency: "Bulgarian Lev",
    code: "BGN",
    icon: "https://flagcdn.com/w20/bg.png",
  },
  {
    country: "Burkina Faso",
    currency: "West African CFA franc",
    code: "XOF",
    icon: "https://flagcdn.com/w20/bf.png",
  },
  {
    country: "Burundi",
    currency: "Burundian Franc",
    code: "BIF",
    icon: "https://flagcdn.com/w20/bi.png",
  },
  {
    country: "Cambodia",
    currency: "Cambodian Riel",
    code: "KHR",
    icon: "https://flagcdn.com/w20/kh.png",
  },
  {
    country: "Cameroon",
    currency: "Central African CFA franc",
    code: "XAF",
    icon: "https://flagcdn.com/w20/cm.png",
  },
  {
    country: "Canada",
    currency: "Canadian Dollar",
    code: "CAD",
    icon: "https://flagcdn.com/w20/ca.png",
  },
  {
    country: "Chile",
    currency: "Chilean Peso",
    code: "CLP",
    icon: "https://flagcdn.com/w20/cl.png",
  },
  {
    country: "China",
    currency: "Chinese Yuan",
    code: "CNY",
    icon: "https://flagcdn.com/w20/cn.png",
  },
  {
    country: "Colombia",
    currency: "Colombian Peso",
    code: "COP",
    icon: "https://flagcdn.com/w20/co.png",
  },
  {
    country: "Costa Rica",
    currency: "Costa Rican Col\u00f3n",
    code: "CRC",
    icon: "https://flagcdn.com/w20/cr.png",
  },
  {
    country: "Croatia",
    currency: "Euro",
    code: "EUR",
    icon: "https://flagcdn.com/w20/hr.png",
  },
  {
    country: "Cuba",
    currency: "Cuban Peso",
    code: "CUP",
    icon: "https://flagcdn.com/w20/cu.png",
  },
  {
    country: "Cyprus",
    currency: "Euro",
    code: "EUR",
    icon: "https://flagcdn.com/w20/cy.png",
  },
  {
    country: "Czech Republic",
    currency: "Czech Koruna",
    code: "CZK",
    icon: "https://flagcdn.com/w20/cz.png",
  },
  {
    country: "Denmark",
    currency: "Danish Krone",
    code: "DKK",
    icon: "https://flagcdn.com/w20/dk.png",
  },
  {
    country: "Djibouti",
    currency: "Djiboutian Franc",
    code: "DJF",
    icon: "https://flagcdn.com/w20/dj.png",
  },
  {
    country: "Dominican Republic",
    currency: "Dominican Peso",
    code: "DOP",
    icon: "https://flagcdn.com/w20/do.png",
  },
  {
    country: "Ecuador",
    currency: "United States Dollar",
    code: "USD",
    icon: "https://flagcdn.com/w20/ec.png",
  },
  {
    country: "Egypt",
    currency: "Egyptian Pound",
    code: "EGP",
    icon: "https://flagcdn.com/w20/eg.png",
  },
  {
    country: "El Salvador",
    currency: "United States Dollar",
    code: "USD",
    icon: "https://flagcdn.com/w20/sv.png",
  },
  {
    country: "Estonia",
    currency: "Euro",
    code: "EUR",
    icon: "https://flagcdn.com/w20/ee.png",
  },
  {
    country: "Ethiopia",
    currency: "Ethiopian Birr",
    code: "ETB",
    icon: "https://flagcdn.com/w20/et.png",
  },
  {
    country: "Fiji",
    currency: "Fijian Dollar",
    code: "FJD",
    icon: "https://flagcdn.com/w20/fj.png",
  },
  {
    country: "Finland",
    currency: "Euro",
    code: "EUR",
    icon: "https://flagcdn.com/w20/fi.png",
  },
  {
    country: "France",
    currency: "Euro",
    code: "EUR",
    icon: "https://flagcdn.com/w20/fr.png",
  },
  {
    country: "Gabon",
    currency: "Central African CFA franc",
    code: "XAF",
    icon: "https://flagcdn.com/w20/ga.png",
  },
  {
    country: "Gambia",
    currency: "Gambian Dalasi",
    code: "GMD",
    icon: "https://flagcdn.com/w20/gm.png",
  },
  {
    country: "Georgia",
    currency: "Georgian Lari",
    code: "GEL",
    icon: "https://flagcdn.com/w20/ge.png",
  },
  {
    country: "Germany",
    currency: "Euro",
    code: "EUR",
    icon: "https://flagcdn.com/w20/de.png",
  },
  {
    country: "Ghana",
    currency: "Ghanaian Cedi",
    code: "GHS",
    icon: "https://flagcdn.com/w20/gh.png",
  },
  {
    country: "Greece",
    currency: "Euro",
    code: "EUR",
    icon: "https://flagcdn.com/w20/gr.png",
  },
  {
    country: "Guatemala",
    currency: "Guatemalan Quetzal",
    code: "GTQ",
    icon: "https://flagcdn.com/w20/gt.png",
  },
  {
    country: "Guinea",
    currency: "Guinean Franc",
    code: "GNF",
    icon: "https://flagcdn.com/w20/gn.png",
  },
  {
    country: "Guyana",
    currency: "Guyanese Dollar",
    code: "GYD",
    icon: "https://flagcdn.com/w20/gy.png",
  },
  {
    country: "Haiti",
    currency: "Haitian Gourde",
    code: "HTG",
    icon: "https://flagcdn.com/w20/ht.png",
  },
  {
    country: "Honduras",
    currency: "Honduran Lempira",
    code: "HNL",
    icon: "https://flagcdn.com/w20/hn.png",
  },
  {
    country: "Hong Kong",
    currency: "Hong Kong Dollar",
    code: "HKD",
    icon: "https://flagcdn.com/w20/hk.png",
  },
  {
    country: "Hungary",
    currency: "Hungarian Forint",
    code: "HUF",
    icon: "https://flagcdn.com/w20/hu.png",
  },
  {
    country: "Iceland",
    currency: "Icelandic Kr\u00f3na",
    code: "ISK",
    icon: "https://flagcdn.com/w20/is.png",
  },
  {
    country: "India",
    currency: "Indian Rupee",
    code: "INR",
    icon: "https://flagcdn.com/w20/in.png",
  },
  {
    country: "Indonesia",
    currency: "Indonesian Rupiah",
    code: "IDR",
    icon: "https://flagcdn.com/w20/id.png",
  },
  {
    country: "Iran",
    currency: "Iranian Rial",
    code: "IRR",
    icon: "https://flagcdn.com/w20/ir.png",
  },
  {
    country: "Iraq",
    currency: "Iraqi Dinar",
    code: "IQD",
    icon: "https://flagcdn.com/w20/iq.png",
  },
  {
    country: "Ireland",
    currency: "Euro",
    code: "EUR",
    icon: "https://flagcdn.com/w20/ie.png",
  },
  {
    country: "Israel",
    currency: "Israeli New Shekel",
    code: "ILS",
    icon: "https://flagcdn.com/w20/il.png",
  },
  {
    country: "Italy",
    currency: "Euro",
    code: "EUR",
    icon: "https://flagcdn.com/w20/it.png",
  },
  {
    country: "Jamaica",
    currency: "Jamaican Dollar",
    code: "JMD",
    icon: "https://flagcdn.com/w20/jm.png",
  },
  {
    country: "Japan",
    currency: "Japanese Yen",
    code: "JPY",
    icon: "https://flagcdn.com/w20/jp.png",
  },
  {
    country: "Jordan",
    currency: "Jordanian Dinar",
    code: "JOD",
    icon: "https://flagcdn.com/w20/jo.png",
  },
  {
    country: "Kazakhstan",
    currency: "Kazakhstani Tenge",
    code: "KZT",
    icon: "https://flagcdn.com/w20/kz.png",
  },
  {
    country: "Kenya",
    currency: "Kenyan Shilling",
    code: "KES",
    icon: "https://flagcdn.com/w20/ke.png",
  },
  {
    country: "Kuwait",
    currency: "Kuwaiti Dinar",
    code: "KWD",
    icon: "https://flagcdn.com/w20/kw.png",
  },
  {
    country: "Kyrgyzstan",
    currency: "Kyrgyzstani Som",
    code: "KGS",
    icon: "https://flagcdn.com/w20/kg.png",
  },
  {
    country: "Laos",
    currency: "Lao Kip",
    code: "LAK",
    icon: "https://flagcdn.com/w20/la.png",
  },
  {
    country: "Latvia",
    currency: "Euro",
    code: "EUR",
    icon: "https://flagcdn.com/w20/lv.png",
  },
  {
    country: "Lebanon",
    currency: "Lebanese Pound",
    code: "LBP",
    icon: "https://flagcdn.com/w20/lb.png",
  },
  {
    country: "Lesotho",
    currency: "Lesotho Loti",
    code: "LSL",
    icon: "https://flagcdn.com/w20/ls.png",
  },
  {
    country: "Liberia",
    currency: "Liberian Dollar",
    code: "LRD",
    icon: "https://flagcdn.com/w20/lr.png",
  },
  {
    country: "Libya",
    currency: "Libyan Dinar",
    code: "LYD",
    icon: "https://flagcdn.com/w20/ly.png",
  },
  {
    country: "Lithuania",
    currency: "Euro",
    code: "EUR",
    icon: "https://flagcdn.com/w20/lt.png",
  },
  {
    country: "Luxembourg",
    currency: "Euro",
    code: "EUR",
    icon: "https://flagcdn.com/w20/lu.png",
  },
  {
    country: "Madagascar",
    currency: "Malagasy Ariary",
    code: "MGA",
    icon: "https://flagcdn.com/w20/mg.png",
  },
  {
    country: "Malawi",
    currency: "Malawian Kwacha",
    code: "MWK",
    icon: "https://flagcdn.com/w20/mw.png",
  },
  {
    country: "Malaysia",
    currency: "Malaysian Ringgit",
    code: "MYR",
    icon: "https://flagcdn.com/w20/my.png",
  },
  {
    country: "Maldives",
    currency: "Maldivian Rufiyaa",
    code: "MVR",
    icon: "https://flagcdn.com/w20/mv.png",
  },
  {
    country: "Mali",
    currency: "West African CFA franc",
    code: "XOF",
    icon: "https://flagcdn.com/w20/ml.png",
  },
  {
    country: "Malta",
    currency: "Euro",
    code: "EUR",
    icon: "https://flagcdn.com/w20/mt.png",
  },
  {
    country: "Mauritania",
    currency: "Mauritanian Ouguiya",
    code: "MRU",
    icon: "https://flagcdn.com/w20/mr.png",
  },
  {
    country: "Mauritius",
    currency: "Mauritian Rupee",
    code: "MUR",
    icon: "https://flagcdn.com/w20/mu.png",
  },
  {
    country: "Mexico",
    currency: "Mexican Peso",
    code: "MXN",
    icon: "https://flagcdn.com/w20/mx.png",
  },
  {
    country: "Moldova",
    currency: "Moldovan Leu",
    code: "MDL",
    icon: "https://flagcdn.com/w20/md.png",
  },
  {
    country: "Monaco",
    currency: "Euro",
    code: "EUR",
    icon: "https://flagcdn.com/w20/mc.png",
  },
  {
    country: "Mongolia",
    currency: "Mongolian T\u00f6gr\u00f6g",
    code: "MNT",
    icon: "https://flagcdn.com/w20/mn.png",
  },
  {
    country: "Montenegro",
    currency: "Euro",
    code: "EUR",
    icon: "https://flagcdn.com/w20/me.png",
  },
  {
    country: "Morocco",
    currency: "Moroccan Dirham",
    code: "MAD",
    icon: "https://flagcdn.com/w20/ma.png",
  },
  {
    country: "Mozambique",
    currency: "Mozambican Metical",
    code: "MZN",
    icon: "https://flagcdn.com/w20/mz.png",
  },
  {
    country: "Myanmar",
    currency: "Burmese Kyat",
    code: "MMK",
    icon: "https://flagcdn.com/w20/mm.png",
  },
  {
    country: "Namibia",
    currency: "Namibian Dollar",
    code: "NAD",
    icon: "https://flagcdn.com/w20/na.png",
  },
  {
    country: "Nepal",
    currency: "Nepalese Rupee",
    code: "NPR",
    icon: "https://flagcdn.com/w20/np.png",
  },
  {
    country: "Netherlands",
    currency: "Euro",
    code: "EUR",
    icon: "https://flagcdn.com/w20/nl.png",
  },
  {
    country: "New Zealand",
    currency: "New Zealand Dollar",
    code: "NZD",
    icon: "https://flagcdn.com/w20/nz.png",
  },
  {
    country: "Nicaragua",
    currency: "Nicaraguan C\u00f3rdoba",
    code: "NIO",
    icon: "https://flagcdn.com/w20/ni.png",
  },
  {
    country: "Nigeria",
    currency: "Nigerian Naira",
    code: "NGN",
    icon: "https://flagcdn.com/w20/ng.png",
  },
  {
    country: "North Korea",
    currency: "North Korean Won",
    code: "KPW",
    icon: "https://flagcdn.com/w20/kp.png",
  },
  {
    country: "North Macedonia",
    currency: "Macedonian Denar",
    code: "MKD",
    icon: "https://flagcdn.com/w20/mk.png",
  },
  {
    country: "Norway",
    currency: "Norwegian Krone",
    code: "NOK",
    icon: "https://flagcdn.com/w20/no.png",
  },
  {
    country: "Oman",
    currency: "Omani Rial",
    code: "OMR",
    icon: "https://flagcdn.com/w20/om.png",
  },
  {
    country: "Pakistan",
    currency: "Pakistani Rupee",
    code: "PKR",
    icon: "https://flagcdn.com/w20/pk.png",
  },
  {
    country: "Panama",
    currency: "Panamanian Balboa",
    code: "PAB",
    icon: "https://flagcdn.com/w20/pa.png",
  },
  {
    country: "Papua New Guinea",
    currency: "Papua New Guinean Kina",
    code: "PGK",
    icon: "https://flagcdn.com/w20/pg.png",
  },
  {
    country: "Paraguay",
    currency: "Paraguayan Guaran\u00ed",
    code: "PYG",
    icon: "https://flagcdn.com/w20/py.png",
  },
  {
    country: "Peru",
    currency: "Peruvian Sol",
    code: "PEN",
    icon: "https://flagcdn.com/w20/pe.png",
  },
  {
    country: "Philippines",
    currency: "Philippine Peso",
    code: "PHP",
    icon: "https://flagcdn.com/w20/ph.png",
  },
  {
    country: "Poland",
    currency: "Polish Zloty",
    code: "PLN",
    icon: "https://flagcdn.com/w20/pl.png",
  },
  {
    country: "Portugal",
    currency: "Euro",
    code: "EUR",
    icon: "https://flagcdn.com/w20/pt.png",
  },
  {
    country: "Qatar",
    currency: "Qatari Riyal",
    code: "QAR",
    icon: "https://flagcdn.com/w20/qa.png",
  },
  {
    country: "Romania",
    currency: "Romanian Leu",
    code: "RON",
    icon: "https://flagcdn.com/w20/ro.png",
  },
  {
    country: "Russia",
    currency: "Russian Ruble",
    code: "RUB",
    icon: "https://flagcdn.com/w20/ru.png",
  },
  {
    country: "Rwanda",
    currency: "Rwandan Franc",
    code: "RWF",
    icon: "https://flagcdn.com/w20/rw.png",
  },
  {
    country: "Saudi Arabia",
    currency: "Saudi Riyal",
    code: "SAR",
    icon: "https://flagcdn.com/w20/sa.png",
  },
  {
    country: "Senegal",
    currency: "West African CFA franc",
    code: "XOF",
    icon: "https://flagcdn.com/w20/sn.png",
  },
  {
    country: "Serbia",
    currency: "Serbian Dinar",
    code: "RSD",
    icon: "https://flagcdn.com/w20/rs.png",
  },
  {
    country: "Seychelles",
    currency: "Seychellois Rupee",
    code: "SCR",
    icon: "https://flagcdn.com/w20/sc.png",
  },
  {
    country: "Sierra Leone",
    currency: "Sierra Leonean Leone",
    code: "SLL",
    icon: "https://flagcdn.com/w20/sl.png",
  },
  {
    country: "Singapore",
    currency: "Singapore Dollar",
    code: "SGD",
    icon: "https://flagcdn.com/w20/sg.png",
  },
  {
    country: "Slovakia",
    currency: "Euro",
    code: "EUR",
    icon: "https://flagcdn.com/w20/sk.png",
  },
  {
    country: "Slovenia",
    currency: "Euro",
    code: "EUR",
    icon: "https://flagcdn.com/w20/si.png",
  },
  {
    country: "Somalia",
    currency: "Somali Shilling",
    code: "SOS",
    icon: "https://flagcdn.com/w20/so.png",
  },
  {
    country: "South Africa",
    currency: "South African Rand",
    code: "ZAR",
    icon: "https://flagcdn.com/w20/za.png",
  },
  {
    country: "South Korea",
    currency: "South Korean Won",
    code: "KRW",
    icon: "https://flagcdn.com/w20/kr.png",
  },
  {
    country: "Spain",
    currency: "Euro",
    code: "EUR",
    icon: "https://flagcdn.com/w20/es.png",
  },
  {
    country: "Sri Lanka",
    currency: "Sri Lankan Rupee",
    code: "LKR",
    icon: "https://flagcdn.com/w20/lk.png",
  },
  {
    country: "Sudan",
    currency: "Sudanese Pound",
    code: "SDG",
    icon: "https://flagcdn.com/w20/sd.png",
  },
  {
    country: "Suriname",
    currency: "Surinamese Dollar",
    code: "SRD",
    icon: "https://flagcdn.com/w20/sr.png",
  },
  {
    country: "Sweden",
    currency: "Swedish Krona",
    code: "SEK",
    icon: "https://flagcdn.com/w20/se.png",
  },
  {
    country: "Switzerland",
    currency: "Swiss Franc",
    code: "CHF",
    icon: "https://flagcdn.com/w20/ch.png",
  },
  {
    country: "Syria",
    currency: "Syrian Pound",
    code: "SYP",
    icon: "https://flagcdn.com/w20/sy.png",
  },
  {
    country: "Taiwan",
    currency: "New Taiwan Dollar",
    code: "TWD",
    icon: "https://flagcdn.com/w20/tw.png",
  },
  {
    country: "Tajikistan",
    currency: "Tajikistani Somoni",
    code: "TJS",
    icon: "https://flagcdn.com/w20/tj.png",
  },
  {
    country: "Tanzania",
    currency: "Tanzanian Shilling",
    code: "TZS",
    icon: "https://flagcdn.com/w20/tz.png",
  },
  {
    country: "Thailand",
    currency: "Thai Baht",
    code: "THB",
    icon: "https://flagcdn.com/w20/th.png",
  },
  {
    country: "Tunisia",
    currency: "Tunisian Dinar",
    code: "TND",
    icon: "https://flagcdn.com/w20/tn.png",
  },
  {
    country: "Turkey",
    currency: "Turkish Lira",
    code: "TRY",
    icon: "https://flagcdn.com/w20/tr.png",
  },
  {
    country: "Turkmenistan",
    currency: "Turkmenistani Manat",
    code: "TMT",
    icon: "https://flagcdn.com/w20/tm.png",
  },
  {
    country: "Uganda",
    currency: "Ugandan Shilling",
    code: "UGX",
    icon: "https://flagcdn.com/w20/ug.png",
  },
  {
    country: "Ukraine",
    currency: "Ukrainian Hryvnia",
    code: "UAH",
    icon: "https://flagcdn.com/w20/ua.png",
  },
  {
    country: "United Arab Emirates",
    currency: "UAE Dirham",
    code: "AED",
    icon: "https://flagcdn.com/w20/ae.png",
  },
  {
    country: "United Kingdom",
    currency: "British Pound",
    code: "GBP",
    icon: "https://flagcdn.com/w20/gb.png",
  },
  {
    country: "United States",
    currency: "US Dollar",
    code: "USD",
    icon: "https://flagcdn.com/w20/us.png",
  },
  {
    country: "Uruguay",
    currency: "Uruguayan Peso",
    code: "UYU",
    icon: "https://flagcdn.com/w20/uy.png",
  },
  {
    country: "Uzbekistan",
    currency: "Uzbekistani Som",
    code: "UZS",
    icon: "https://flagcdn.com/w20/uz.png",
  },
  {
    country: "Venezuela",
    currency: "Venezuelan Bol\u00edvar",
    code: "VES",
    icon: "https://flagcdn.com/w20/ve.png",
  },
  {
    country: "Vietnam",
    currency: "Vietnamese Dong",
    code: "VND",
    icon: "https://flagcdn.com/w20/vn.png",
  },
  {
    country: "Yemen",
    currency: "Yemeni Rial",
    code: "YER",
    icon: "https://flagcdn.com/w20/ye.png",
  },
  {
    country: "Zambia",
    currency: "Zambian Kwacha",
    code: "ZMW",
    icon: "https://flagcdn.com/w20/zm.png",
  },
  {
    country: "Zimbabwe",
    currency: "Zimbabwean Dollar",
    code: "ZWL",
    icon: "https://flagcdn.com/w20/zw.png",
  },
];

export const uniqueCurrencies = [...new Set(currencies.map((item) => item.code))].map(
  (item) => {
    return { label: item, value: item };
  }
);
